# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipingTunnel < Formula
  desc "Tunneling from anywhere with Piping Server"
  homepage "https://github.com/nwtgck/go-piping-tunnel"
  version "0.9.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0/piping-tunnel-0.9.0-darwin-amd64.tar.gz"
    sha256 "17eb6fd9cd2a189cbfcb0c42b66dbd9937fbc2432d822506b193254034836a96"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0/piping-tunnel-0.9.0-darwin-arm64.tar.gz"
    sha256 "5141c33317ac8e501b8a6217498b0a1b104b1e8ff1c0e0a6a03cda06c0a267ef"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0/piping-tunnel-0.9.0-linux-amd64.tar.gz"
    sha256 "e472efe4d859a8350eade7ec1e07d5a601edd3432040d200c6e827e2d61317a9"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0/piping-tunnel-0.9.0-linux-armv6.tar.gz"
    sha256 "edd018b93c2f75cca91dfb32a13cdd90cf900721c39024535157333f7b553f58"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0/piping-tunnel-0.9.0-linux-arm64.tar.gz"
    sha256 "0f4e92986afe9f07b637e01d5c086455db3694a4e1345cf0d36e02e9b1e4e94c"
  end

  def install
    bin.install "piping-tunnel"
  end
end
