# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipingTunnel < Formula
  desc "Tunneling from anywhere with Piping Server"
  homepage "https://github.com/nwtgck/go-piping-tunnel"
  version "0.9.0-pmux6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0-pmux6/piping-tunnel-0.9.0-pmux6-darwin-amd64.tar.gz"
    sha256 "4312f5e6ba554fa39c6738c878e7acab7aa2e910520ce59fee8679af7ea71a1b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0-pmux6/piping-tunnel-0.9.0-pmux6-darwin-arm64.tar.gz"
    sha256 "b94e20fa8183b21ad702ddae5e46dac252456d79d9ee966a513182e3cd20deeb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0-pmux6/piping-tunnel-0.9.0-pmux6-linux-amd64.tar.gz"
    sha256 "0794593eded5c9bbed7f77d53d15ad26a01b320a85a6b3dae2d640140a72e530"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0-pmux6/piping-tunnel-0.9.0-pmux6-linux-armv6.tar.gz"
    sha256 "da7ae7456cacd2f8bbe12811c48cc4b26fbd15f450389b256ff539334a251bd7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-tunnel/releases/download/v0.9.0-pmux6/piping-tunnel-0.9.0-pmux6-linux-arm64.tar.gz"
    sha256 "3cdc3e490241785a1a738495ab5457808014764c1ea8b24f3491e400a9b9ffb0"
  end

  def install
    bin.install "piping-tunnel"
  end
end
